In [3]:
import numpy as np
from numpy import random

In [19]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.25, 0.55, 0.1], size=(100))

my_x = set(x)

from collections import Counter

my_count = dict(Counter(x))

print(my_count)

my_x = my_count.keys()
my_y = my_count.values()

{7: 59, 9: 7, 3: 8, 5: 26}


### Split array with one missing element

In [45]:
arr6 = np.array(range(15))
np.array_split(arr6,4)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14])]

### Array stack

In [39]:
arr1 = np.array([34,56,78])
arr2 = np.array([25,32,17])
arr3 = np.stack((arr1,arr2))
arr4 = np.stack((arr1,arr2),axis=1)
arr5 = np.dstack((arr1,arr2))
print(arr3),print("\n")
print(arr4),print("\n")
print(arr5)


[[34 56 78]
 [25 32 17]]


[[34 25]
 [56 32]
 [78 17]]


[[[34 25]
  [56 32]
  [78 17]]]


### Enumerate items from a 2D array into a dictionary

In [31]:
my_arr_4 = np.array([[1,2,3],[4,5,6]])
my_dict_1 = {}
for kx,vx in np.ndenumerate(my_arr_4):
    my_dict_1[kx] = vx
my_dict_1

{(0, 0): 1, (0, 1): 2, (0, 2): 3, (1, 0): 4, (1, 1): 5, (1, 2): 6}

### Enumerate items from an array into a dictionary

In [19]:
my_arr_3 = np.array(range(25,500,5))
my_arr_3

array([ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,  80,  85,
        90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150,
       155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215,
       220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280,
       285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345,
       350, 355, 360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410,
       415, 420, 425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475,
       480, 485, 490, 495])

In [27]:
my_dict = {}
for kx,vx in np.ndenumerate(my_arr_3):
    my_dict[str(kx[0])] = vx
print(my_dict)
    

{'0': 25, '1': 30, '2': 35, '3': 40, '4': 45, '5': 50, '6': 55, '7': 60, '8': 65, '9': 70, '10': 75, '11': 80, '12': 85, '13': 90, '14': 95, '15': 100, '16': 105, '17': 110, '18': 115, '19': 120, '20': 125, '21': 130, '22': 135, '23': 140, '24': 145, '25': 150, '26': 155, '27': 160, '28': 165, '29': 170, '30': 175, '31': 180, '32': 185, '33': 190, '34': 195, '35': 200, '36': 205, '37': 210, '38': 215, '39': 220, '40': 225, '41': 230, '42': 235, '43': 240, '44': 245, '45': 250, '46': 255, '47': 260, '48': 265, '49': 270, '50': 275, '51': 280, '52': 285, '53': 290, '54': 295, '55': 300, '56': 305, '57': 310, '58': 315, '59': 320, '60': 325, '61': 330, '62': 335, '63': 340, '64': 345, '65': 350, '66': 355, '67': 360, '68': 365, '69': 370, '70': 375, '71': 380, '72': 385, '73': 390, '74': 395, '75': 400, '76': 405, '77': 410, '78': 415, '79': 420, '80': 425, '81': 430, '82': 435, '83': 440, '84': 445, '85': 450, '86': 455, '87': 460, '88': 465, '89': 470, '90': 475, '91': 480, '92': 485, '

### Converting numbers to string from an array

In [17]:
for y in np.nditer(my_arr_2, flags=['buffered'], op_dtypes='S'):
    print(y)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


### List all elements of array irrespective of how many dimensions array has

In [8]:
my_arr_2 = np.array([[1, 2, 3],[4, 5, 6]])
for x in np.nditer(my_arr_2):
    print(x)

1
2
3
4
5
6


### Convert 1D array to 3D array

In [15]:
my_arr_1 = np.array(range(64),ndmin=3)
my_arr_1

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
         48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]])

### basics

In [6]:
my_array = np.array(range(5))
my_array

array([0, 1, 2, 3, 4])

In [7]:
print(np.__version__)

1.20.2
